### PR TITLE
fix fragment called twice

### PR DESCRIPTION
**Pull request by nmyggg**
### fragment called twice on backup

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [ ] New feature
* [ ] Translation
* [x] General refinement
* Other:

### Details

Please provide more details about changes if necessary.

### CODE REVIEW

**Comment by madeye** [comment]
Cool, thanks!

**Comment by Mygod** [comment]
What the? This thing doesn't even compile.

**Comment by Mygod** [comment]
@nmyggg Thank you for trying to make money off our work and violating the GPLv3 license. Don't you think I can't see what you're trying to do there. I've fully reverted your change to the original repo. If you still think your change is relevant, please do the following:

1. Fix your code, at least get it to compile;
2. Open another pull request;
3. Describe what you're trying to fix because I really can't tell.

@madeye Would you at least wait for Travis build to finish before merging random PRs please?

**Comment by madeye** [comment]
Hmm, my bad...

**Pull request merged**
