### PR TITLE
Plugin lib 1.3.0

### LINKED ISSUE #1091: kcp插件无法启动
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
android 7.0
* Device: *e.g. Google Pixel XL*
华为p8
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
v4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:rc4-md5
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [x ] Auto Connect
* [ x] TCP Fast Open
* [ ] NAT mode

### What did you do?
使用kcp插件连接失败，提示”服务启动失败，无法连接远程服务器：unknow plugin kcptun”
远程端口连接kcp端口，参数autoexpire=10;mode=fast
。

### What did you expect to see?

请问kcp插件如何使用

### PR DESCRIPTION
**Pull request by Mygod**
Read commit messages for more information. Tested locally with updated v2ray-plugin-android that I will push later.

This should hopefully fix #1091 and #1106 but I have not tested since I do not own a device that can reproduce them.

### CODE REVIEW

**Comment by Mygod** [comment]
For client see: https://github.com/shadowsocks/v2ray-plugin-android/commit/6c58c30b67fe2122e8eed975741647fec617b1b9 (luckily this does not require the release of 1.3.0 lib)

**Comment by Mygod** [comment]
@madeye Do you have a Huawei device that can test #1091?

**Comment by madeye** [comment]
Yeah, I'm using Huawei Mate 20. I think #1091 is already fixed by Huawei on Android P.

Also tested latest commit. Everything works well.

**Comment by Mygod** [comment]
Hmm... According to Crashlytics (5c93a35af8b88c2963f27cf3), this still happens and >1/3 of them are Android 9 devices (including a Huawei Honor Play and Honor V9). This issue also non-negligibly occurs for vendors including ADVAN, EVERCROSS, vivo, LENOVO among others.

**Comment by Mygod** [comment]
Before 1.3:

```
I/ActivityManager: Start proc 23494:com.github.shadowsocks.plugin.v2ray/u0a382 for content provider com.github.shadowsocks.plugin.v2ray/.BinaryProvider
```

After killing plugin app proc and installing updated apps, `ActivityManager` no longer outputs `Start proc` line so I have high confidence that this should resolve the issue.

**Pull request merged**
