### PR TITLE
Implement SIP004, SIP002

### PR DESCRIPTION
**Pull request by Mygod**
### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [x] New feature
* [ ] Translation
* [ ] General refinement
* Other:

### Details

See commit logs for details.

### CODE REVIEW

**Comment by wongsyrone** [comment]
missing two ciphers

**Comment by Mygod** [comment]
@wongsyrone Yeah I think now's a good time to remove them. https://github.com/shadowsocks/shadowsocks-android/pull/1103/commits/44a1ec3e7c86c86c6861911b145f263d362cb1a1

**Comment by wongsyrone** [comment]
= =|||

chacha20-poly1305
chacha20-ietf-poly1305
and if you are using master branch
xchacha20-ietf-poly1305

**Comment by Mygod** [comment]
@wongsyrone Oh yeah! My bad.

**Comment by Mygod** [comment]
@wongsyrone Oh yeah! My bad.

**Comment by wongsyrone** [comment]
I suggest not adding xchacha20-ietf-poly1305 atm, and waiting for next libsodium release.

**Comment by Mygod** [comment]
@wongsyrone Reason? (did I miss something?)

**Comment by wongsyrone** [comment]
API may get changed, the author also suggests to use the stable branch or released version.
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/core.c#L21

**Comment by wongsyrone** [comment]
You can change submodule to https://github.com/jedisct1/libsodium/commit/2f4f718cd94adab547c210a78050762cf667dfca, this is the tagged 1.0.11

**Comment by Mygod** [comment]
@wongsyrone Done. Thanks.

**Comment by Mygod** [comment]
@madeye Doesn't [this](https://github.com/shadowsocks/shadowsocks-libev/blob/05d5121/src/aead.c#L156) imply mbed TLS doesn't support chacha20-poly1305 AEADs?

**Comment by wongsyrone** [comment]
It is just a mask.
For mbedtls, they may merge https://github.com/ARMmbed/mbedtls/pull/485. Who knows?

**Comment by madeye** [comment]
Yes, it's just a mask. All chacha20 related ciphers are handled by libsodium.

**Comment by Mygod** [comment]
@madeye I think it's ready now. Please review.

**Pull request merged**
