### PR TITLE
Show traffic in notification

### PR DESCRIPTION
**Pull request by Mygod**
This is actually what I had in mind when opening #440.

TODO: Disabling this new feature causes weird behaviors:

1. The change doesn't apply immediately;
2. Shutting down service doesn't update UI normally.

I can't figure out why or how to fix it though. It seems like something about inter-process things. :-(

### CODE REVIEW

**Comment by madeye** [comment]
I think it's safe to keep traffic stat always enabled.

**Comment by Mygod** [comment]
Traffic stat is always enabled. But I decided to let user pick whether they want to show the current tx/rx rate in notification or not. However that doesn't work well...

**Comment by madeye** [comment]
I suggest not to add more settings. The UI is already too complicated... Let's keep post speed to the notification.

**Comment by Mygod** [comment]
Alright. Removed it for now. Please review the code. I did a force close and a reset to make it work so there might be more bugs...

**Comment by madeye** [comment]
OK, I will check them later.

**Comment by madeye** [comment]
What are the steps to reproduce "Shutting down service doesn't update UI normally."? I tried the change locally and it works very well.

**Comment by madeye** [comment]
OK, the issue is already fixed by removing the "disable the new feature" option...

**Comment by Mygod** [comment]
Yes. Checkout the previous commit to see the bug.

**Pull request merged**
