### PR TITLE
Let Android system extract native libraries

### PR DESCRIPTION
**Pull request by Mygod**
### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [ ] New feature
* [ ] Translation
* [x] General refinement
* Other:

### Details

Advantage:

* No more worries about inconsistencies about native libraries and extracting them (therefore no more ETXTBSY errors);
* Native libraries are counted in App section instead of Data section in storage information.

Disadvantage:

* Executable names have to be `lib*.so` otherwise Android system won't extract it.

### CODE REVIEW

**Comment by madeye** [comment]
It looks quite interesting. I didn't know we can do this before.

**Comment by wongsyrone** [comment]
I think

> Executable names have to be lib*.so otherwise Android system won't extract it.

should be included into commit message

**Comment by Mygod** [comment]
Another advantage is that we don't need to chmod by ourselves. However because of its disadvantage we should be cautious about merging this. What do you think?

**Comment by madeye** [comment]
I don't think the disadvantage matters. Is this approach also works on Android 4.4?

**Comment by Mygod** [comment]
Only tested on Android 7.0.

**Comment by madeye** [comment]
OK, let me test it first.

**Comment by madeye** [comment]
Tested on Android 4.4. Everything works fine. Let's merge this change.

**Comment by Mygod** [comment]
I noticed that after this change, installing debug apk takes 5 seconds to 1 minute longer. I wonder if it's caused by some kind of Android optimization or gdb_server.

**Comment by madeye** [comment]
@Mygod The release apk seems to work fine. No delay observed.

**Comment by wongsyrone** [comment]
Might related to https://developer.android.com/studio/command-line/zipalign.html

**Comment by Mygod** [comment]
zipalign is not relevant since it's done in the compilation process.

**Pull request merged**
