### PR TITLE
Fix a issue in ProcessUtils

### PR DESCRIPTION
**Pull request by JLLK**
Fix a issue in ProcessUtils

### CODE REVIEW

**Comment by Mygod** [comment]
Acceptable but clumsy.

**Comment by madeye** [comment]
In which situation, we need this `pName.startsWith(SHADOWNSOCKS) && pName.length > SHADOWNSOCKS.length && pName.charAt(SHADOWNSOCKS.length) != ':')`?

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/pull/583#issuecomment-188777766

**Comment by madeye** [comment]
Should `pname == SHADOWSOCKS` be enough?

**Comment by madeye** [comment]
Also, why not get the process name though Android API? For example: http://stackoverflow.com/questions/8542326/android-how-to-get-the-processname-or-packagename-by-using-pid

**Comment by Mygod** [comment]
I prefer this solution.
http://stackoverflow.com/a/21389402/2245107

**Comment by madeye** [comment]
@Mygod OK, so there is a bug of ActivityManager.
@JLLK Could you refine your solution following the link provided by @Mygod?

**Comment by Mygod** [comment]
@madeye I prefer this one just because getting all processes is an overkill imo.

And keep using `/proc/self/cmdline`.

**Comment by JLLK** [comment]
There is a trick like this:

```
> adb shell cat /proc/1822/cmdline
/data/data/com.github.shadowsocks/tun2socks--netif-ipaddr26.26.26.2--netif-netmask255.255.255.0--socks-server-addr127.0.0.1:1080--tunfd48--tunmtu1500--sock-path/data/data/com.github.shadowsocks/sock_path--loglevel3--dnsgw26.26.26.1:8153%
```

So we have to use `startsWith` to judge process rather than the whole name.

**Comment by Mygod** [comment]
It's actually NULL (`\0`) terminated/separated so just follow that link please.

**Comment by madeye** [comment]
Forget to mention: Please avoid any`/data/data/com.github.shadowsocks` in your code. Use `getApplicationInfo.dataDir` instead.

IMO, if you just want to identify the JVM processes like `com.github.shadowsocks`or `com.github.shadowsocks:vpn`, a simple comparison should be enough.

**Comment by madeye** [comment]
Merged. Thanks!

**Comment by Mygod** [comment]
Much better. :smile:

**Pull request merged**
