### PR TITLE
Add secondary remote dns support.

### PR DESCRIPTION
**Pull request by V-E-O**
### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [x] New feature
* [ ] Translation
* [ ] General refinement
* Other:

### Details

Add secondary remote dns support:
192.168.1.1,192.168.1.2
In certain scenario, one may use own custom dns server.
Well, hard code secondary dns 208.67.222.222 may be annoying.
This provides a way to change it.

BTW:
remove duplicated "import java.net.InetAddress" is for "强迫症".

### CODE REVIEW

**Comment by Mygod** [comment]
Secondary DNS isn't the same as alternative DNS in overture afaic. However we can probably support secondary remote DNS.

**Comment by madeye** [comment]
LGTM.

**Comment by V-E-O** [comment]
@Mygod Yes, the alternative dns in overture is usually the untainted dns.
When in bypass chn/gfw list mode alternative dns is user defined remote dns like 8.8.8.8 , but in other modes like global mode, user can only set primary dns and may want to modify this untainted dns which is hard coded with 208.67.222.222.
The result of 208.67.222.222 may be higher priority than user defined primary dns, especially using customized dns (for me, I have customized some dns records conflicting with 208.67.222.222).
This provide a compatible way to implement it without break others.

**Comment by Mygod** [comment]
In that case, perhaps DNS forwarding would work for you?

**Comment by V-E-O** [comment]
My problem can be resolved by disabling AlternativeDNS in ALL/BYPASS_LAN mode.
PrimaryDNS will be enough when you are just need to forwarding the dns, right?
I think overture's OnlyPrimaryDNS config is suitable for this scenario.

And for Secondary DNS, I'm rolling out a patch to set dns list into overture config.
Close this one for deprecated.

**Pull request closed without merging**
