### PR TITLE
Plugin 2.0.1

### PR DESCRIPTION
**Pull request by Mygod**
Needs more testing. Main change is using new fragment result API from androidx.fragment 1.3.

### CODE REVIEW

**Review by madeye — APPROVED** [review]

**Comment by Mygod** [comment]
We should maybe fix #2678 too. Also [jcenter is being a *responsible* platform and going bye bye](https://developer.android.com/studio/build/jcenter-migration).

**Comment by madeye** [comment]
#2678 should be fixed now. 2.0.0 is uploaded months ago.

**Comment by Mygod** [comment]
Sounds good. This PR is good to go.

**Review by mrkoikoi — COMMENTED** [review]
https://basic.bravedns.com/1:AIBAAQ==

**Pull request merged**
