### PR TITLE
Plugin 2.0.0

### LINKED ISSUE #2576: DNS bugs on 5.13 pls fix it.
Please read contributing guidelines. Thanks.

**Describe the bug**
unable to resolve hostname with smartDNS  on remote server on 5.13.
but 5.12 is fine.
smartDNS listen to udp DNS request on 53.
also 
smartDNS listen to tcp DNS request on 53.
**To Reproduce**
1. 5.1.3
2. remote server uses smartDNS or dnsmsq to unlock stream, like Netflix
3. set remote DNS 127.0.0.1 or 0.0.0.0
4. VPN mode 
5. unable to resolve hostname

**Expected behavior**
5.12 and below works fine with the mentioned process. 
And 5.13 can not resolve DNS no matter set remote DNS to 0.0.0.0/127.0.0.1 or 8.8.8.8/1.1.1.1 .
pls, fix it.
**Smartphone (please complete the following information):**
 - Android 10
 - Device:  Google Pixel 3 XL
 - Last version 

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 127.0.0.1 or 0.0.0.0
* [ x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

### PR DESCRIPTION
**Pull request by Mygod**
@madeye Please help finish this implementation, thanks! You can read `isV2` here: https://github.com/shadowsocks/shadowsocks-android/blob/1783420a89e46c39524e9beeb7a7dac919b36ad0/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L105

Fixes #2576.

### CODE REVIEW

**Comment by Mygod** [comment]
@madeye Do you think we should use a less hacky name, like `__android_vpn` instead of `V`?

**Comment by madeye** [comment]
yeah, but it requires updating a lot of plugins...

**Comment by madeye** [comment]
tested with simple-obfs, it should work now.

**Comment by Mygod** [comment]
> yeah, but it requires updating a lot of plugins...

We already break a lot of plugins anyway so why not do it properly this time?

**Comment by madeye** [comment]
PR is welcome... I will help merge them...

**Comment by Mygod** [comment]
No hurry. :rofl:

**Comment by Mygod** [comment]
Why force push over my commit?

**Comment by madeye** [comment]
My bad, reverted.

**Comment by Mygod** [comment]
It looks like it still does not contain cd6a1f1d8025fe87c473b447835f7437f9b77c1b and f9a80ac6158be65bf3395854188e83c86861acff.

**Comment by madeye** [comment]
Can you push it again? It looks I did something wrong here.

**Comment by madeye** [comment]
Everything should be reverted now. 😅

**Review by madeye — APPROVED** [review]
LGTM.

**Comment by Mygod** [comment]
Merge and do a release? Also I think shadowsocks-rust updated `plugin-arg` (string) to `plugin-args` (array) in master so when we update shadowsocks-rust we need to implement that change too...

**Pull request merged**
