### PR TITLE
Enhancements for Android Q beta

### PR DESCRIPTION
**Pull request by Mygod**
Things worth looking into:

* [x] New `VpnService.Builder.setMetered` API.
* [x] New non-blocking `DnsResolver` API.
* [x] [NfcAdapter.setNdefPushMessage](https://developer.android.com/reference/android/nfc/NfcAdapter.html#setNdefPushMessage(android.nfc.NdefMessage,%20android.app.Activity,%20android.app.Activity...)) is deprecated. (should we remove this feature?) (update: #2211)

### CODE REVIEW

**Comment by LiveChief** [comment]
Please approve this, i really need this :)

**Comment by Mygod** [comment]
Updated to API 29. Ready to merge.

**Comment by Mygod** [comment]
@madeye Any comments?

**Comment by madeye** [comment]
I'm traveling now. I'll take a look next week.

**Comment by Mygod** [comment]
Looks like there will not be a PR for Android R this year, maybe except for [`LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS).

**Pull request merged**
