### PR TITLE
Blue formatting tool

### PR DESCRIPTION
**Pull request by grihabor**
Hi! 

I'm working on ultimate kotlin formatting tool called [blue](https://gitlab.com/grihabor/blue/). I'd like you to have a look at it, so I've formatted the projects with this tool.

### CODE REVIEW

**Comment by madeye** [comment]
It looks the tool broke the build: https://circleci.com/gh/shadowsocks/shadowsocks-android/236

**Comment by grihabor** [comment]
Yep, I'm looking into it

**Comment by grihabor** [comment]
@madeye Fixed

**Comment by Mygod** [comment]
I know this tool is still in development but this code style...

me no likey

P.S. I would probably call it blakk if I were to develop black for Kotlin.

**Comment by yunpengsnail** [comment]
try it

**Pull request closed without merging**
