### PR TITLE
Allow show password

### PR DESCRIPTION
**Pull request by Mygod**

### CODE REVIEW

**Comment by Mygod** [comment]
DO NOT MERGE. Succeeded by https://github.com/Gericop/Android-Support-Preference-V7-Fix/pull/182.

**Comment by Mygod** [comment]
@madeye Do you think this feature would be a good addition at all?

**Comment by madeye** [comment]
Maybe not, as the password would not be readable at all.

**Comment by Mygod** [comment]
Okay.

**Comment by Mygod** [comment]
@madeye Hmm, why would the password be not readable?

**Comment by Mygod** [comment]
@madeye I'm considering reviving this PR. Currently the profiles can already be exported so I don't see why we need to hide the password.

**Comment by madeye** [comment]
I think we need to hide password by default, as a best practice. 

Showing password would be useful, but optional.

**Pull request closed without merging**
