### PR TITLE
Use Chinese (Taiwan) translation as fallback for other Chinese locales

### PR DESCRIPTION
**Pull request by Mygod**
#615 makes Shadowsocks display in English for Chinese locales if it is neither Chinese (China) nor Chinese (Taiwan).

I choosed Chinese (Taiwan) for other Chinese locales. Here's my reasons.

* In my device (CyanogenMod 13), the only other Chinese locale I have is Chinese (Hong Kong) which uses traditional Chinese characters.
* According to [Wikipedia](https://en.wikipedia.org/wiki/Simplified_Chinese_characters#Education), traditional Chinese characters are more commonly used by Chinese native speakers outside of mainland China.

What do you think? @madeye @LNDDYL

### CODE REVIEW

**Comment by LNDDYL** [comment]
我的意見是：「影梭」這個名稱只用於中文(中國大陸)[zh-CN]上，其他語系均使用其英文名稱「Shadowsocks」。

**Comment by LNDDYL** [comment]
@Madeye @Mygod 為什麼把zh-TW移除了？

**Comment by madeye** [comment]
It makes zh-TW the default locales of Chinese, not removing it.

**Comment by LNDDYL** [comment]
意義何在？

**Pull request merged**
