### PR TITLE
update gradle wrapper to 4.4.1

### PR DESCRIPTION
**Pull request by wongsyrone**
$ ./gradlew wrapper --gradle-version=4.4.1 --distribution-type=all

### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [ ] New feature
* [ ] Translation
* [x] General refinement
* Other:

### Details

update gradle wrapper via official doc

### CODE REVIEW

**Comment by Mygod** [comment]
Where did you get the script from?

**Comment by wongsyrone** [comment]
which script?

I'm using Archlinux and have gradle installed. In fact, I just execute `gradle wrapper --gradle-version=4.4.1 --distribution-type=all` in the project folder and these files got changed.

**Comment by wongsyrone** [comment]
There are two distribution types: all and bin, to keep in sync with the current one, I'm using all, while bin should work as well since all have sources included.

**Comment by wongsyrone** [comment]
If you mean the cmdline, check 'Upgrade with the Gradle Wrapper' section in https://gradle.org/install/

**Comment by wongsyrone** [comment]
Found another reading if you have interest: https://medium.com/@bherbst/understanding-the-gradle-wrapper-a62f35662ab7, it shows almost the same way as mine to upgrade.

**Comment by Mygod** [comment]
Sounds good.

**Pull request merged**
