### PR TITLE
update acl list

### PR DESCRIPTION
**Pull request by pexcn**

### CODE REVIEW

**Comment by Mygod** [comment]
Source?

**Comment by madeye** [comment]
Please provide your source.

**Comment by pexcn** [comment]
https://github.com/pexcn/shadowsocks-android/tree/acl and https://github.com/pexcn/shadowsocks-android/tree/gh-pages very ugly code... :sweat_smile::sweat_smile:

**Comment by pexcn** [comment]
china ip list: https://github.com/pexcn/daily/blob/gh-pages/chnroute/chnroute.txt
and script: https://github.com/pexcn/daily/blob/master/scripts/chnroute/chnroute.sh

**Comment by madeye** [comment]
Thanks! Merged.

**Pull request merged**
