### PR TITLE
Implement custom rules

### LINKED ISSUE #1009: Add custom rules for policy route
As the support of hostname rules becomes stable, I think it's time to add custom rules feature. Any suggestion @Mygod ?

Also, I found this project is quite interesting (https://github.com/twiceyuan/SSRules). Maybe we can help to integrate it into our app.

Also open an issue in that project: https://github.com/twiceyuan/SSRules/issues/2

### PR DESCRIPTION
**Pull request by Mygod**
Fix #1009 finally!

### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [x] New feature
* [ ] Translation
* [ ] General refinement
* Other:

### Details

Custom rules. An editor is included.

TODO (can merge for now): Quick scroll.

### CODE REVIEW

**Comment by madeye** [comment]
Wow! That's a huge change. Let me try it first 😃

**Comment by Mygod** [comment]
Yes. Didn't expect it would take so much time.

**Comment by madeye** [comment]
After trying this new feature, I have to say it's exactly what I want! To be honest, I can't do better. 👍

**Comment by madeye** [comment]
The change looks good to me. If there is any issue found in the future, I can help to fix.

Merged. Thanks!

**Pull request merged**
