### PR TITLE
Update RU translation

### PR DESCRIPTION
**Pull request by VladWinner**

### CODE REVIEW

**Comment by Mygod** [comment]
Thanks but please contribute your translations via POEditor. (See README.)

**Comment by VladWinner** [comment]
That's exactly what I did before the pull request. However, I noticed that the changes made by users before me (some of them were made a year ago) were not added in the last build.

**Comment by Mygod** [comment]
I will try to remember to pull it in the next update. (When I get to it.)

**Comment by VladWinner** [comment]
I hope this also will fix the display here.
✓ English:
Screenshot_20220326-103537_Shadowsocks
✗ Russian (current, before PR)
Screenshot_20220326-103156_Shadowsocks

**Comment by zhaoweih** [comment]
LGTM

**Comment by VladWinner** [comment]
@Mygod v5.3.0-preview:
Screenshot_20220624-004040_Shadowsocks
It looks much better, but the localization isn't updated.

**Pull request closed without merging**
