### PR TITLE
Split ABIs for smaller apk size

### PR DESCRIPTION
**Pull request by Mygod**
### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [ ] New feature
* [ ] Translation
* [x] General refinement
* Other:

### Details

With this change, apk size will go down to <6MB.

### CODE REVIEW

**Comment by madeye** [comment]
Let's keep it open. Currently, I don't want to split ABIs.

It's always hard to educate the users which APK they should download.

**Comment by Mygod** [comment]
How about creating two flavors one being universal and the other being split abis?

**Comment by wongsyrone** [comment]
> It's always hard to educate the users which APK they should download.

Agreed.

**Comment by madeye** [comment]
@Mygod It's a good idea.

**Comment by Mygod** [comment]
Unfortunately there doesn't seem to be a way to do this. Settings `split` in variants applies globally.

**Comment by Mygod** [comment]
Update: According to [this](https://stackoverflow.com/a/33230181/2245107), most devices including x86 can run armv7 just fine. We can just simply put armv7 on top.

**Comment by madeye** [comment]
What about the x86 emulator?

**Comment by Mygod** [comment]
I haven't tested yet but probably not since libhoudini is proprietary code. But if somebody wants to play around with emulators, they might as well learn what CPU architectures are already.

Nexus Player uses x86 and [it has libhoudini included since the beginning](https://android.googlesource.com/device/asus/fugu/+/b7e4ded70cd2c71abaa89a16799b29e508781f2d%5E%21/self-extractors/intel/staging/device-partial.mk) and many other Android x86 devices as well.

**Comment by madeye** [comment]
Unless someone would like to run our APK on an AMD device, I think it's safe to remove x86 binaries from our release build.

**Comment by Mygod** [comment]
What about split abis? I still think putting armv7 as the first apk in GitHub releases is a good idea. :)

**Comment by madeye** [comment]
Sure, if there is no issue for x86, I think we can move on to split ABIs.

**Comment by Mygod** [comment]
Conflicts resolved. Please review. @madeye

**Comment by Mygod** [comment]
I just realized there IS a way to make a universal apk (and it's literally called universal apk).

**Pull request merged**
