### PR TITLE
Support build overture on Windows

### PR DESCRIPTION
**Pull request by imReker**

### CODE REVIEW

**Comment by madeye** [comment]
Cool! Thanks for the patch!

**Comment by imReker** [comment]
And, the Go bundled in Overture can be compiled in WSL on Windows 10, so gcc for Windows and blablabla is not required.
Download Linux Go binary, export GOROOT_BOOTSTRAP, and make.bash in overture/go/src

**Comment by darkii321** [comment]
Build command failed.


Error while executing process C:\Users\Mycomputer\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib -j2 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib\x86" >NUL 2>NUL || rem


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbserver      ": "[i686-linux-android] C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib/x86/gdbserver"


copy /b/y "C:\Users\Mycomputer\AppData\Local\Android\Sdk\ndk-bundle\build\\..\prebuilt\android-x86\gdbserver\gdbserver" "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib\x86\gdbserver" > NUL


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Gdbsetup       ": "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86" > C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBupild\derobcess_beugg\lib/ixn8:6 /Cgdb.rseeattuepP
rocess(NULL, 


"C":,/U s.e.r.s)/ Dfeabiorlae/dA.p
pData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support/include C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++ C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/libancillary C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/mbedtls/include C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/pcre/dist C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/badvpn/lwip/src/include/ipv4 C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/badvpn/lwip/src/include/ipv6 C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/badvpn/lwip/custom" >> C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\lib/x86/gdb.setup


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\jni-helper" >NUL 2>NUL || rem


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o.d -gcc-toolchain C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -


make: *** No rule to make target `C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/libancillary/fd_recv.c', needed by `C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/ancillary/libancillary/fd_recv.o'.  Stop.


g -fno-exceptions -fno-rtti -O0 -UNDEBUG -fno-limit-debug-info  -IC:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/libancillary -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support/include -IC:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/jni-helper.cpp -o C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/jni-helper/jni-helper.o


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\obj\local\x86" >NUL 2>NUL || rem


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\debug\obj\local\x86\objs-debug\cpufeatures" >NUL 2>NUL || rem


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O0 -UNDEBUG -fno-limit-debug-info  -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/libcpufeatures.a C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/cpufeatures/cpu-features.o


Build command failed.


Error while executing process C:\Users\Mycomputer\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Mycomputer\Desktop\shadowsocks\core\src\main\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\release\lib -j2 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\jni-helper" >NUL 2>NUL || rem


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -IC:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/libancillary -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++abi/include -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/support/include -IC:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/jni-helper.cpp -o C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\release\obj\local\x86" >NUL 2>NUL || rem


md "C:\Users\Mycomputer\Desktop\shadowsocks\core\build\intermediates\ndkBuild\release\obj\local\x86\objs\cpufeatures" >NUL 2>NUL || rem


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "Compile        ": "cpufeatures <= cpu-features.c"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -MMD -MP -MF C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument p-rocess_begin: CreateProcess(NULL, "", ...) failed.
no-canonical-


make: *** No rule to make target `C:/Users/Mycomputer/Desktop/shadowsocks/core/src/main/jni/libancillary/fd_recv.c', needed by `C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.prefixes -g -O2 -DNDEBUG  -IC:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstaco'.  Stop.
krealign  --sysroot C:/Users/Mycomputer/App


Data/Local/Android/Sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sysroot/usr/include/i686-linux-android -c  C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/android/cpufeatures/cpu-features.c -o C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [x86] "StaticLibrary  ": "libcpufeatures.a"


C:/Users/Mycomputer/AppData/Local/Android/Sdk/ndk-bundle/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar crsD  C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a C:/Users/Mycomputer/Desktop/shadowsocks/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o

**Comment by ac1991** [comment]
@TroyRay 上面那个报错你解决了吗？

**Comment by CreaterXu** [comment]
Do you slove this error? i have the same error, @darkii321

**Comment by ZaeemSattar** [comment]
Anyone got solution to this problem please share your comments with me :) mail me on zaeem.dcs.gcu@gmail will be happy to listen to you.
@lqtian @CreaterXu @TroyRay @darkii321

**Comment by DamonMinko** [comment]
Have you got the solution? Please share!

**Comment by Mygod** [comment]
Please post questions at the forum at https://discourse.shadowsocks.org/c/implementations/shadowsocks-android instead.

**Pull request merged**
