### PR TITLE
Change some words

### PR DESCRIPTION
**Pull request by yyxida**
### Type of changes

* [ ] Bugfix
* [ ] New feature
* [x] Translation
* [ ] General refinement
* Other:

### Details

Please provide more details about changes if necessary.

Change some words

# **The next time upload a full translation**

### CODE REVIEW

**Comment by Mygod** [comment]
Thanks for your translation. By the way I just added a [wiki page for translators](https://github.com/shadowsocks/shadowsocks-android/wiki/Guidelines-for-translation-contributors). You might want to check on that page. :stuck_out_tongue:

**Comment by yyxida** [comment]
@Mygod what is values-ja-rJP？I'm boob

**Comment by yyxida** [comment]
↑↑↑noob↑↑↑ not boob

**Comment by Mygod** [comment]
>So you should use `values-ja` instead of `values-ja-rJP`.

**Comment by yyxida** [comment]
but you tell me is values-ja

**Comment by Mygod** [comment]
Yes.

**Comment by yyxida** [comment]
resConfigs := Seq("ja", "ru", "zh-rCN", "zh-rTW")

so。。。What should I do

**Comment by yyxida** [comment]
By the way
I'm not good at English

**Pull request merged**
