### PR TITLE
make connection test url configurable

### PR DESCRIPTION
**Pull request by V-E-O**
### Type of changes

_Put an `x` inside the [ ] that applies._

* [ ] Bugfix
* [x] New feature
* [ ] Translation
* [ ] General refinement
* Other:

### Details

When SS is used in China as a pure secure proxy, the hardcoded connection test Google server may not work.
Here I added two global URL configuration, one for China List mode, one for else.

### CODE REVIEW

**Comment by V-E-O** [comment]
Oops, Codacy reported the ConstantNaming issue (uppercase), seems that we need some unification for the original code here.

**Comment by madeye** [comment]
Please don't add two URLs, One test URL is already enough.

**Comment by V-E-O** [comment]
@madeye My first version is one URL, but after my concern is that it may break original design (ChinaList mode using qualcomm.cn).
You guys make decision, I will pull the one URL version later.

**Comment by Mygod** [comment]
Wait what? I don't see this change necessary.

**Comment by V-E-O** [comment]
@Mygod I believe it's usefull when you just use SS as a secure proxy within China's internet, because hardcoded www.google.com/generate_204 breaks the connectivity test feature.
Also my first patch (two configrable url) does not "kills off" any "feature".

**Comment by Mygod** [comment]
This app isn't going to cover every single use case ever.

**Comment by Mygod** [comment]
Connectivity test is never meant to be a core feature - you don't see stuff like this in other clients. You could always use your browser to test if stuff works. If I merge changes like this, the next thing you know is that you'll have hundreds of (mostly useless) configuration options in this app. Additional rule for ChinaList mode is there since it doesn't complicates the UI too much.

But feel free to make forks if you think this is useful to you.

**Comment by V-E-O** [comment]
Other user scenario like this one https://github.com/shadowsocks/shadowsocks-android/issues/1603
If your server is built on ADSL with dyn IP, broken connectivity test is painful.

**Comment by V-E-O** [comment]
I've a fork version, but to maintain and build is a heavy stuff.
Suppose you don't want UI change, what if check both two URL (Google and Qualcomm) in the backend?

**Pull request merged**
