### PR TITLE
Is this a Material Design 2?

### LINKED ISSUE #1868: I got an crash, when start shadowsocks!!!!
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Android version: "5.1"*
Device: NEXUS5
android os: ***cyanogenmod 12.1***
Shadowsocks version: version code "v4.6.1" or commit ID "c6676b50df0225cd5f94add09e203a558e98937f"

### What did you do?
build it by myself, but the apk don't work. I got some crash below!!!!
do something throw [Crash When App Start](https://github.com/shadowsocks/shadowsocks-android/issues/1866), but it no use.  
I install the release apk, “shadowsocks--universal-4.6.1.apk”， it also error。
### What did you see instead?
```
07-12 10:33:48.320 6433-6433/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.shadowsocks, PID: 6433
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5294)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
     Caused by: kotlin.KotlinNullPointerException
        at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620) 
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 

```

### PR DESCRIPTION
**Pull request by Mygod**
Bugs blocked by upstream:

* https://github.com/material-components/material-components-android/commit/b1a784ce7525990b6379ab221e44de9fa41df20c
* https://github.com/material-components/material-components-android/pull/182

Fixes #1868.

### CODE REVIEW

**Comment by madeye** [comment]
Hmm, I just find an issue:

screen

Steps to reproduce:

1. Switch to settings.
2. Scroll down to the bottom.
3. Switch back to profiles.

**Comment by madeye** [comment]
BTW, the button would be overlapped with list view.

Maybe it's not a good idea to put the buffer in the middle.

screen

**Comment by Mygod** [comment]
Yes I'm aware of the two issues you mentioned. I think the overlapping issue isn't too serious IMO but feel free to fix it.

**Comment by madeye** [comment]
I find any padding or margin in BottomAppBar would make FloatingActionButton detached from BottomAppBar.

It looks the library assumes no complex view in BottomAppBar, or is it just a bug?

**Comment by Mygod** [comment]
My bad. I forgot to attach this: https://gist.github.com/Mygod/95f4c934adc7082008bfccc1ce31c83c

You can use this `BottomAppBarFix` to see what it would be like after https://github.com/material-components/material-components-android/pull/182 is merged.

**Comment by madeye** [comment]
It looks this change is being blocked by upstream.

Any chance we can fix it locally or have a fork to unblock ourselves?

**Comment by Mygod** [comment]
You can use the `BottomAppBarFix` I mentioned above. But I only consider this to be a minor UI defect so I don't want to keep that in the source code and maintain it.

**Comment by terrycriswell** [comment]
--------------------------------------------
On Thu, 8/23/18, Max Lv <notifications@github.com> wrote:

 Subject: Re: [shadowsocks/shadowsocks-android] Is this a Material Design 2? (#1903)
 To: "shadowsocks/shadowsocks-android" <shadowsocks-android@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Thursday, August 23, 2018, 10:51 PM
 
 It looks this change
 is being blocked by upstream.
 Any chance we can fix it locally or have a fork to
 unblock ourselves?
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Mygod** [comment]
Upstream has fixed this issue accidentally while they were trying to do something else. So just wait for the next release I guess.

**Comment by Mygod** [comment]
1.0.0-rc02 has released, unfortunately it doesn't contain the fix.

**Comment by madeye** [comment]
It looks we're still being blocked by upstream fixes.

**Comment by Mygod** [comment]
I'm expecting them to release the fix in the next version.

**Pull request merged**
