### PR TITLE
New UI with drawer (#762)

### PR DESCRIPTION
**Pull request by Mygod**
I have finished implementing new things for this new UI. What remains to be done is to fix these things now. DON'T MERGE BEFORE FINISHING THESE.

* [x] New banner? (assigned to @madeye)
* [x] License information in new files; (`/.headache.cfg`) (assigned to @madeye)
* [x] More thorough tests! (for example, editing should be disabled when connecting/stopping, etc.) (assigned to @Mygod)
* [x] Test & fix tasker features; (assigned to @Mygod)
* [x] Localizations; (assigned to @madeye)
* [x] Remove resources that are no longer used; (assigned to @Mygod)
* [x] Final review by @Mygod. (because I can't add myself to the reviewers :disappointed:)

P.S. Snackbar animation is broken, but that isn't a big issue for now. :stuck_out_tongue: Oh and please don't squash and merge for this PR.

After finishing this, we can start working on #1006 #1009 #1021. :tada:

### CODE REVIEW

**Comment by madeye** [comment]
Yes, I think we can merge now.

**Comment by Mygod** [comment]
No I meant the drawer background. There are still plenty of things to fix yet.

**Comment by madeye** [comment]
Yes, I think so. But if any better image shows up in the future, I may replace it.

Or maybe one day we can provide a "theme picker", users can buy new themes from Google Play. 😸

**Comment by Mygod** [comment]
We're almost there! Would you please help with localization? There are still native strings in the scala files and layout resources file that needs moving to strings.xml.

**Comment by Mygod** [comment]
I also tried to make a minidrawer which failed. See [my minidrawer branch](https://github.com/Mygod/shadowsocks-android/commit/0732dd598172a00a295b6904b70fb683bb96c280) for more information.

**Comment by Mygod** [comment]
@madeye Ready to merge. Please review again and merge.

**Comment by madeye** [comment]
Cool! I'm merging it.

**Pull request merged**
