### PR TITLE
Recover unexpected process exit on MIUI

### LINKED ISSUE #499: MiUI7开发版12.10后台内存清理自动结束tun2socks、ss-local
在MiUI上后台管理界面上滑锁住应用防止自动清理后，MiUI自带清理依然会结束tun2socks及ss-local导致无法继续使用。明前尚不明确是针对SS进行的定点清除还是MiUI逻辑问题（因为只有tun2socks及ss-local被杀掉）

### PR DESCRIPTION
**Pull request by ayanamist**
fix #499
I'm not familiar with scala, so use Java instead to implement some classes.
Tested on Xiaomi 4c Dev 6.3.3

### CODE REVIEW

**Comment by ayanamist** [comment]
It has a timeout, it will sleep 1 second and then check process which prevents fast-fail.
I learned scala a little before, and don't like its present situation. Why insisting on writing Scala?

**Comment by madeye** [comment]
Yes, I noticed the timeout. A better way is to stop restarting if it's a fast-fail, to avoid battery drain.

Sorry, but this project only accepts pull requests in Scala because I'm a fanboy of Scala. :smile:

**Comment by ayanamist** [comment]
OK, i changed to stop loop when fast-fail.
I also changed to scala. The converted code can not compile, so i waste hours to make it compiling, and ran into [this bug](https://issues.scala-lang.org/browse/SI-8162) so i have to extract a method `initThread`
Now i hate scala ever than before, and will prevent its usage in all my projects.

**Comment by madeye** [comment]
Merged, thanks! I will refine the code later.

**Comment by CzBiX** [comment]
@ayanamist You can take a try with Kotlin as a better replacement.

**Comment by ayanamist** [comment]
@CzBiX I know Kotlin as a more simpler than Scala and better than Java programming language, however, this project is only receiving scala pr as above mentioned.

**Comment by Mygod** [comment]
@madeye Well I suppose we could've merged this and done the java-to-scala conversion ourselves.

**Comment by madeye** [comment]
@Mygod Yes, we can do this for further pull requests.

**Pull request merged**
