### PR TITLE
Add KCP support

### PR DESCRIPTION
**Pull request by madeye**
Add KCP support for shadowsocks.

KCPTUN should be setup on a different port to avoid conflicts with Shadowsocks' UDP support.

### CODE REVIEW

**Comment by codexss** [comment]
希望在服务端也集成这个功能

**Comment by cj1324** [comment]
👍

**Comment by Mygod** [comment]
Shouldn't we provide a more reasonable default value for [`kcpcli`](https://github.com/shadowsocks/shadowsocks-android/pull/788/files#diff-e538750d345d58bb7a056d5e3b86d09dR109), like `--crypt none --sndwnd 1024 --mode fast --nocomp`?

**Comment by Mygod** [comment]
@madeye What do you think?

**Comment by madeye** [comment]
I'm doing experiments for best parameters. Currently, I'm using `--crypt none --mode normal --mtu 1200 --nocomp --dscp 46 -datashard 10 -parityshard 0`

**Comment by Mygod** [comment]
@madeye Should we use `--crypt none --mode normal --mtu 1200 --nocomp --dscp 46 -datashard 10 -parityshard 0` as the default value for now?

**Comment by madeye** [comment]
@Mygod Yes, I think so.

**Pull request merged**
