### PR TITLE
Fix parser bug, add share profile by NFC.

### PR DESCRIPTION
**Pull request by AnyOfYou**
The old setMessage(profiles.mkString("\n")) made profiles iterator point to end before it being use.

Use Android Beam or NFC tag to add profile.

### CODE REVIEW

**Comment by Mygod** [comment]
Using toList or sth like that would be better imo.

**Comment by AnyOfYou** [comment]
The problem is also about showing user string representation of Profile object is not useful.

**Comment by Mygod** [comment]
Oops I meant to write `profiles.map(Parser.generate).mkString("\n")`.

**Comment by madeye** [comment]
Merged, thanks!

**Pull request merged**
