### PR TITLE
fix https://github.com/shadowsocks/shadowsocks-android/issues/2215

### PR DESCRIPTION
**Pull request by jhoneybee**
I added a small feature to test the node's network  fix https://github.com/shadowsocks/shadowsocks-android/issues/2215

image

### CODE REVIEW

**Comment by madeye** [comment]
You should no rely on ping to do the test.

Actually, the test should take advantage of ss-local to perform a real connection test, e.g. connect to `google.com` through the proxy.

**Comment by jhoneybee** [comment]
> You should no rely on ping to do the test.
> 
> Actually, the test can take advantage of `ss-local` to perform a real connection test, e.g. connect to `google.com` through the proxy.

 I'm not very familiar with ss-local. I'll try to use this.

> can I use ```SonarLint``` plug-in as a code specification?

**Comment by jhoneybee** [comment]
@madeye  
I found that my code specification did not conform to ```Codacy/PR Quality Review'.``` 

> Is there a plug-in for Android studio?

**Comment by Mygod** [comment]
That is a very wasteful way to do ping as well. If you just want to do a ping test, you can easily write a bash script that is much easier.

**Comment by jhoneybee** [comment]
> That is a very wasteful way to do ping as well. If you just want to do a ping test, you can easily write a bash script that is much easier.

Thank you very much for correcting my mistake.


Then I will do two things 

1. use ```ss-local``` test connection 
2. test network latency in other ways

Is there any better advice for testing network latency?

**Comment by jhoneybee** [comment]
> That is a very wasteful way to do ping as well. If you just want to do a ping test, you can easily write a bash script that is much easier.

@Mygod  Excuse me, an additional topic, what plug-ins do you use to check code specifications?

**Comment by Mygod** [comment]
If you would still like to implement this feature, I would suggest to focus on implementing it first.

And to answer your question directly, no.

**Comment by Mygod** [comment]
To be honest, I don't see why you care about batch testing latency (whose expected value hardly ever changes) instead of throughput, jitter, etc.

**Comment by jhoneybee** [comment]
> To be honest, I don't see why you care about batch testing latency (whose expected value hardly ever changes) instead of throughput, jitter, etc.

Thank you very much. I'm an application-level developer. I don't know much about the underlying code, or even the network jitter. I'll find out about this convenient information.


> I'll close this request first and implement it in a better way in the future. Now I'm going to learn about ```ss-local``` code.

**Comment by jhoneybee** [comment]
> You should no rely on ping to do the test.
> 
> Actually, the test can take advantage of `ss-local` to perform a real connection test, e.g. connect to `google.com` through the proxy.

@Mygod  I'm sorry, but I'd like to ask you how to call dynamic link libraries in the project.

>  Sorry, I am a newbie. It doesn't seem to be using JNI pattern calls

**Comment by jhoneybee** [comment]
@Mygod I'm sorry, but I'd like to ask you how to call dynamic link libraries in the project.

> Sorry, I am a newbie. It doesn't seem to be using JNI pattern calls

**Comment by diov** [comment]
> @Mygod I'm sorry, but I'd like to ask you how to call dynamic link libraries in the project.
> 
> > Sorry, I am a newbie. It doesn't seem to be using JNI pattern calls

Actually, they build the executable binaries but name them with *.so suffix. It's tricky but very useful, LOL.
So you can call the dynamic link libraries with `ProcessBuild` or `Runtime.exex()` easily. Also, you can check the [Makefile script](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/jni/build-shared-executable.mk) to find how it works.

**Comment by jhoneybee** [comment]
> > @Mygod I'm sorry, but I'd like to ask you how to call dynamic link libraries in the project.
> > > Sorry, I am a newbie. It doesn't seem to be using JNI pattern calls
> 
> Actually, they build the executable binaries but with *.so suffix naming. It's tricky but very useful, LOL.
> You can check the [Makefile script](https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/jni/build-shared-executable.mk) to find how it works.
> So you can call the dynamic link libraries with `ProcessBuild` or `Runtime.exex()` easily, without JNI pattern calls.

I have been looking for jni mode calls, the direction is wrong, thank you very much

**Pull request closed without merging**
