### PR TITLE
Add strings zh-TW

### PR DESCRIPTION
**Pull request by LNDDYL**

### CODE REVIEW

**Comment by madeye** [comment]
Merged, thanks!

**Comment by LNDDYL** [comment]
@madeye 此次更新何時會呈現在Google Play上面？

**Comment by madeye** [comment]
In the next release.

**Comment by LNDDYL** [comment]
@madeye 那麼，下一次發行(the next release)是什麼時候？

**Comment by madeye** [comment]
No particular schedule.

**Comment by LNDDYL** [comment]
呃，好吧…

**Comment by rockstore** [comment]
execuse me, what ide do you use to develop?

**Pull request merged**
