### PR TITLE
Migrate to androidx.preference 1.1.0

### PR DESCRIPTION
**Pull request by Mygod**
This PR upgrades preference library to 1.1.0 (currently in alpha but it is actually already used in [v2ray-plugin-android](https://github.com/shadowsocks/v2ray-plugin-android)) and removes Gericop's preferencex which no longer seems to be updated.

Also allows show password. See also #1948.

Update: Blocked by https://issuetracker.google.com/issues/124356533.

### CODE REVIEW

**Comment by Mygod** [comment]
Oh lord TV preference looks a lot much more uglylylylier now.

**Comment by Mygod** [comment]
Enjoy this glorious failure in full 4K png.
glorious failure

**Comment by madeye** [comment]
Hmm, let's wait for future releases of this library...

**Comment by Mygod** [comment]
Bug still present on 1.1.0-alpha04.

**Pull request closed without merging**
