### PR TITLE
Update ACL IPs

### PR DESCRIPTION
**Pull request by pexcn**
APNIC 的数据不是很完整，加上了 IPIP 免费版的数据：
https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
https://github.com/17mon/china_ip_list/raw/master/china_ip_list.txt

相关 issue:
https://github.com/17mon/china_ip_list/issues/6
https://github.com/rssnsj/network-feeds/issues/34

最后经过 [cidrmerge](http://cidrmerge.sourceforge.net) 合并。

Telegram IPs 来源是：
https://bgp.he.net/search?search%5Bsearch%5D=telegram&commit=Search
最后也经过 cidrmerge 合并。

EDIT:
GFWList 的数据不知道怎么生成，还没更新。

### CODE REVIEW

**Comment by pexcn** [comment]
相关 issue: https://github.com/shadowsocks/shadowsocks-android/issues/1891
希望能自动更新，手动更新可能没及时覆盖到相关的 IP

**Comment by pexcn** [comment]
@Mygod You can refer my script https://github.com/pexcn/daily but it's not support ss-android.

**Comment by pexcn** [comment]
https://github.com/pexcn/daily/blob/master/scripts/chnroute/chnroute.sh

**Comment by madeye** [comment]
Generally, I don't think a daily updated CHN route is really necessary.

In fact, I didn't update CHN IP related rules on my routers for years and it still works quite well.

**Comment by pexcn** [comment]
Or weekly/monthly?
Frequently updates feeling more IP will be coverage.

About CIDR address merge function, what tools are used to implement it?
[cidrmerge](http://cidrmerge.sourceforge.net) or [aggregate](http://horms.net/projects/aggregate/) or [netmask & ipv4-merger](https://github.com/rssnsj/network-feeds/tree/master/ipset-lists/tools) or implement by yourself?

It is worth noting, `netmask & ipv4-merger` seems have some bug? see: https://github.com/rssnsj/network-feeds/issues/35

**Comment by madeye** [comment]
@pexcn You may submit a separate pull request for your scripts. If so, we can run that script before each release.

**Comment by pexcn** [comment]
@madeye I am not good at bash shell script, not clear how to implement it.
So I put the simple script here :sweat_smile::

```bash
#!/bin/bash -e

CHINALIST='chinalist.txt'

APNIC_URL='https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest'
IPIP_URL='https://github.com/17mon/china_ip_list/raw/master/china_ip_list.txt'
APNIC='apnic.txt'
IPIP='ipip.txt'

gen_ipv4_chinalist() {
  curl -kLs ${APNIC_URL} | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > ${APNIC}
  curl -kLs ${IPIP_URL} > ${IPIP}
  cat ${APNIC} ${IPIP} | aggregate -q > ${CHINALIST}
}

function clean_up() {
  rm -f ${APNIC} ${IPIP}
}

gen_ipv4_chinalist
clean_up
```

**Pull request merged**
