### PR TITLE
Refactor subscriptions

### PR DESCRIPTION
**Pull request by Mygod**
Probably finish up tonight.

### CODE REVIEW

**Comment by madeye** [comment]
Cool, hope we can have a pre-release next week.

**Comment by Mygod** [comment]
@madeye Hmm wouldn't it make more sense to simply use an EditText for all the subscription URLs?

**Comment by madeye** [comment]
I think it's much better to have a fragment to manage all subscriptions...

**Comment by Mygod** [comment]
EditText allows for copy/paste batch actions though.

**Comment by madeye** [comment]
One concern is that it would be hard to validate each URL, like reporting insecure URLs.

Given we already have the subscription fragment, I don't think we should remove it. At least, we can extend subscription based on this for future development, e.g. subscription traffic statics.

**Comment by Mygod** [comment]
Okay. Should we extend this feature to tv?

**Comment by madeye** [comment]
On TV, I think one EditText should be good enough.

With subscription support on TV, I think we can improve the Google Play score a lot...

**Comment by Mygod** [comment]
Alright. Not sure what future extensions you are planning for but I will try to keep changes minimal. :)

**Comment by Mygod** [comment]
Hmm I'm currently getting `java.lang.VerifyError: Verifier rejected class com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1: java.lang.Object com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(java.lang.Object) failed to verify: java.lang.Object com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(java.lang.Object): [0x14A] 'this' argument 'Uninitialized Reference: com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1$4 Allocation PC: 328' not instance of 'Precise Reference: com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1$2' (declaration of 'com.github.shadowsocks.subscription.SubscriptionService$onStartCommand$1$invokeSuspend$$inlined$map$lambda$1' appears in /data/app/com.github.shadowsocks-MdKJd5Xmv6syOmQxl84ysw==/base.apk!classes4.dex)`. Seems like compiler bug.

**Comment by Mygod** [comment]
I cannot be bothered to make a minimal example to reproduce this error and report to Kotlin.

@madeye Can you help test this?

**Comment by madeye** [comment]
Sure.

**Comment by perqin** [comment]
Will libev port implement this subscription mechanism? I am wondering how this feature will be implemented by those ports without GUI. I am using libev port on my Linux desktop, and it will be nice to have subscription support.

**Pull request merged**
