### PR TITLE
Update README.md with F-Droid button

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get the TV version of the app on F-Droid 👍

### CODE REVIEW

**Comment by Mygod** [comment]
Hmm? What is this? I don't recollect supporting F-droid.

**Comment by eighthave** [comment]
f-droid.org is a free software app store, where all apps are reviewed and built from source.  Since this app is free software, an F-Droid contributor packaged it for inclusion in f-droid.org

**Comment by Mygod** [comment]
No plan to support f-droid.

**Comment by shuvashish76** [comment]
> I don't recollect supporting F-droid.

There is a criteria for original author consent or to notify about F-Droid inclusion. (and does not oppose the inclusion)
I hope they informed you before adding this to F-Droid.

> No plan to support f-droid.

Wut? Recently your app added to F-Droid (https://www.f-droid.org/packages/com.github.shadowsocks/) & the Source Code linked to this repo. It's okay if you don't wanna add F-Droid badge to README page but it's already there.

**Pull request closed without merging**
