### PR TITLE
Add support for Android TV

### LINKED ISSUE #762: Redesign Android TV interface
(so that Google Play can stop rejecting this app)
# Redesign mobile UI
- [x] Switch to preference lib in Android Support lib. (wow we even switched to a third-party support lib fix lib now)
- [x] Redesign mobile interface with drawers.
- [x] Make profiles page the main UI.
# Redesign TV UI
- [x] Create submodules for TV, mobile and core. (did it in the beta branch)
- [ ] Split functionalities.
- [ ] Redesign TV interface with LeanbackPreferenceFragment.

### PR DESCRIPTION
**Pull request by Mygod**
Fix #762. Screenshot for Android P emulator:

screenshot_1535012699

This pull request also contains various fixes for mobile module. I'm too lazy to separate it out. Also only basic features are ported.

What's not ported and won't be ported by me:

* Profile configuration; (sorry nobody wants to type on TV)
* NFC/QR code/clipboard;
* Custom rules;
* Night mode;
* Tasker support.

A file manager is required for this port to work. I'd recommend MiXplorer if there isn't one available.

TODO:

* [x] Travis weird bug;
* [x] A separate Crashlytics ID for TV; (might not be necessary, needs testing)
* [x] Ads? (@madeye)
* [x] Share over LAN as a TV-only feature? (should we implement this @madeye)
* [x] Version code in sync? (4060210)
* [ ] Update POEditor;
* [ ] FAQ and open source licenses.

### CODE REVIEW

**Comment by Mygod** [comment]
A related change has been submitted to AOSP: https://android-review.googlesource.com/c/platform/frameworks/support/+/736762

**Comment by madeye** [comment]
Cool! I'll try it on my Shield first.

BTW, no need to put an Ad in TV view. Let's see how many people would use shadowsocks on a TV.

**Comment by Mygod** [comment]
I have already tested it on my Shield (darcy 2017) and Sony Bravia TV.

@madeye Could you set up crashlytics for TV app as well?

**Comment by madeye** [comment]
Sure

**Comment by Mygod** [comment]
Uhh what about open source licenses?

**Comment by madeye** [comment]
Hmm, add a link to the README?

**Comment by Mygod** [comment]
Well unfortunately not even NVIDIA shield has a browser built-in, trying to ACTION_OPEN a link will crash the app.

**Comment by madeye** [comment]
Okay, thought it would be an easy task.

**Comment by Mygod** [comment]
What about add a shortened URL like `shadowsocks.org/android/licenses` and put it at the end?

**Comment by madeye** [comment]
Good idea, it should work.

**Comment by Mygod** [comment]
@madeye I just realized we forgot to update `https://shadowsocks.org/acl/android/v1/$route.acl`. It should point to `core` instead of `mobile` now.

**Comment by madeye** [comment]
Oops, updated now.

**Pull request merged**
